env: "local" #local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "http://happybirthdaydima.ru/"
  timeout: 4s #время на чтение запроса и такое же время на отправку ответа
  idle_timeout: 60s #время жизни соединения с клиентом